### PR TITLE
Update utils.py

### PR DESCRIPTION
**Pull request by alphonse-xavier-924**
Updated the date and time format in the Noise Level & Trend box.

@danieltsoukup , please let me know if there are any changes to be made to the date and time format. I made sure that the noise level date and date picker formatting are consistent. Thanks.

### CODE REVIEW

**Comment by danieltsoukup** [comment]
HI @alphonse-xavier-924 welcome to the project, thanks for the contribution. Have you tested locally if the two dates are showing consistently? That util function is only used in the trend box and you have to set the display format for the date picker separately. Also, the function is typed to return a datetime but you are actually returning string in this case.
image

**Comment by alphonse-xavier-924** [comment]
Hi @danieltsoukup , Thank you for catching the type of the value that the function returns. Does the format MM/DD/YYYY e.g. 08/11/2024 work for you? If you have any particular date format in mind please let me know. Once I have an understanding of the required format, I will go ahead and update both the trend box and the display format for the date picker. Thanks.

**Comment by danieltsoukup** [comment]
Thanks @alphonse-xavier-924 and sorry for the confusion! Let's do "DD MMM YYYY" for the date part of both, and it suffices for the trend box to show down to minutes so "DD MMM YYYY, HH:MM". Could you adjust the `month_format` as well for the date picker? For example:
- Trend box: "12 Aug 2024, 10:00"
- Date picker display: "12 Aug 2024"
- Month format in date picker dropdown: "Aug 2024"
image

**Comment by alphonse-xavier-924** [comment]
Hi @danieltsoukup ,Thanks for the clarification. I will work on the changes.

**Pull request closed without merging**
